# Makefile for PGPLOT.
# ./makemake /opt/space/sw/PGPLOT/pgplot linux g77_gcc
# This file is automatically generated. Do not edit.
#
# This generates the PGPLOT binary files (libraries and demos) in the
# current default directory (which need not be the source directory).
#-----------------------------------------------------------------------
include Makefile.in
SHELL=/bin/sh
#
RM = rm -f
EEXT =
OEXT = .o
OUTEXT = .ps
OUTFILE = simple$(OUTEXT)
#	PGPLOT subdirectories
SRC=.
#
# Fortran compiler and compilation flags
#
FCOMPL=g77
FFLAGC=-u -Wall -fPIC -O
FFLAGD=-fno-backslash
FC=g77
#
# C compiler and compilation flags
#
XINCL=-I/usr/include/X11
MOTIF_INCL=-I/usr/include/X11 -IXm
ATHENA_INCL=-I/usr/include/X11
TK_INCL=-I/usr/include -I/usr/include/X11 -I/usr/include/tcl8.6
RV_INCL=
CCOMPL=gcc
CFLAGC=-Wall -fPIC -DPG_PPU -O -I.
CFLAGD=-Wall -O
MCOMPL=
MFLAGC=
#
# Pgbind flags.
#
PGBIND_FLAGS=bsd
#
# Loader library-flags
#
XLIBS=-L/usr/lib/x86_64-linux-gnu -lX11
PNGLIBS=-lpng -lz
LDFLAGS=
PGLOCDIR=x86_64-linux-gnu
PGPLOT_DIR=`pwd`/$(PGLOCDIR)
MOTIF_LIBS=-lXm -lXt $(XLIBS)
ATHENA_LIBS=-lXaw -lXt -lXmu -lXext $(XLIBS)
TK_LIBS=-L/usr/lib -ltk -ltcl $(XLIBS) -ldl
#
#	Loader command for PGPLOT library
#
PGPLOT_LIB=-L`pwd` $(PGLOCDIR)/libpgplot.a $(PNGLIBS) $(XLIBS)
CPGPLOT_LIB=-L`pwd` $(PGLOCDIR)/libcpgplot.a $(PNGLIBS) $(XLIBS)
#
# Shared library creation.
#
SHARED_LIB=libpgplot.so
SHARED_LD=gcc -shared  -o libpgplot.so
#
# The libraries that the shared PGPLOT library depends upon.
# This is for systems that allow one to specify what libraries
# undefined symbols of a shared library reside in. Such systems
# (eg. Solaris 2.x) use this information at run time so that users of
# the library don't have to list a slew of other implementation-specific
# libraries when they link their executables.
#
SHARED_LIB_LIBS=
#
# Ranlib command if required
#
RANLIB=ranlib
#
# Routine lists.
#
TARGETS=pgdem1$(EEXTE) simple$(OEXTE)
#
DEMDIR= .
#-----------------------------------------------------------------------
# Target "all" makes everything (except the library of obsolete routines)
#-----------------------------------------------------------------------
all: $(TARGETS)
	@echo ' ';echo '*** Finished compilation of PGPLOT example ***';echo ' '
	@echo 'Note that the following files may be needed.'
	@echo ' (it depends on the pgplot features you use)'
	@echo '       libpgplot.a'
	@echo '       libpgplot.so'
	@echo '       grfont.dat'
	@echo '       rgb.txt'
	@echo '       pgdisp'
	@echo '       pgxwin_server'
	@echo '       libXmPgplot.a'
	@echo '       XmPgplot.h'
	@echo '       libXaPgplot.a'
	@echo '       XaPgplot.h'
	@echo '       libtkpgplot.a'
	@echo '       tkpgplot.h'
	@echo ' '
	@echo 'Also note that subsequent usage of PGPLOT programs requires that'
	@echo 'the full path of the chosen installation directory be named in'
	@echo 'an environment variable named PGPLOT_DIR.'
	@echo 'during this build PGPLOT_DIR was set to '$(PGPLOT_DIR)
	@echo ' '

#-----------------------------------------------------------------------
# Rules for compiling the $(OEXT) files
#-----------------------------------------------------------------------


DISPATCH_ROUTINE=grexec$(OEXT)

grexec$(OEXT): grexec.f
	$(FCOMPL) -c $(FFLAGC) grexec.f

#-----------------------------------------------------------------------
# Target "lib" is used to built the PGPLOT subroutine library.
# libpgplot.a is the primary PGPLOT object library.
# "shared" is an optional target for operating systems that allow shared
# libraries.
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Target "prog" is used to make the demo programs. They can also be made
# individually.
#-----------------------------------------------------------------------
prog: $(TARGETS)

pgdem1$(OEXT): pgdem1.f
	$(FCOMPL) -c $(FFLAGC) $?

pgex0$(OEXT): pgex0.f
	$(FCOMPL) -c $(FFLAGC) $?

pgex1$(OEXT): pgex1.f
	$(FCOMPL) -c $(FFLAGC) $?

pgdem1$(EEXT): pgdem1$(OEXT) pgex0$(OEXT) pgex1$(OEXT)
	$(FCOMPL) -dynamiclib -lgfortran -static-libgfortran  $(FFLAGD) -o $@ $?  \
	-L`pwd` $(PGLOCDIR)/libpgplot.a $(PGLOCDIR)/libXaPgplot.a \
	$(PGLOCDIR)/libXmPgplot.a $(PGLOCDIR)/libX11.a $(PGLOCDIR)/libxcb.a \
	$(PGLOCDIR)/libXau.a $(PGLOCDIR)/libXdmcp.a \
	$(PGLOCDIR)/libpng16.a $(PGLOCDIR)/libz.a $(PGLOCDIR)/libquadmath.a -ldl


simple: $(DEMDIR)/simple$(OEXT)
	$(FCOMPL) $(FFLAGD) -o $@ $? $(PGPLOT_LIB) $(LDFLAGS)

#-----------------------------------------------------------------------
# Target "grfont.dat" is the binary font file.
# This is created from grfont.txt with the "pgpack" program.
#    (a) compile the `pgpack' program; then
#    (b) run `pgpack' to convert the ASCII version of the font file
#    (grfont.txt) into the binary version (grfont.dat). When executed,
#    `pgpack' should report:
#	Characters defined:   996
#	Array cells used:   26732
#-----------------------------------------------------------------------


#-----------------------------------------------------------------------
# Documentation files
#-----------------------------------------------------------------------



#-----------------------------------------------------------------------
# Target "libxmpgplot.a" contains the Motif widget driver.
#-----------------------------------------------------------------------

cleancpgdemo:
	$(RM) cpgdemo cpgdemo$(OEXT)

cpgdemo$(OEXT): cpgplot.h cpgdemo.c $(PGLOCDIR)/libcpgplot.a
	$(RM) cpgdemo cpgdemo$(OEXT)
	$(CCOMPL) $(CFLAGD) -c -I. cpgdemo.c

cpgdemo: cpgdemo$(OEXT) $(PGLOCDIR)/libcpgplot.a $(PGLOCDIR)/libpgplot.a
	$(RM) cpgdemo;\
	$(FCOMPL) -dynamiclib -lgfortran -static-libgfortran -fno-backslash \
	-o cpgdemo $?  \
	$(PGLOCDIR)/libXaPgplot.a \
        $(PGLOCDIR)/libXmPgplot.a $(PGLOCDIR)/libX11.a $(PGLOCDIR)/libxcb.a \
        $(PGLOCDIR)/libXau.a $(PGLOCDIR)/libXdmcp.a \
        $(PGLOCDIR)/libpng16.a $(PGLOCDIR)/libz.a $(PGLOCDIR)/libquadmath.a -ldl; \
	$(RM) cpgdemo$(OEXT)


#-----------------------------------------------------------------------
# Target "install" is required for Figaro.
#-----------------------------------------------------------------------
install:

run: pgprog1
	./pgprog1 < pgplot_type.conf
static: pgdem1$(OEXT)  pgex0$(OEXT)  pgex1$(OEXT)
	$(FCOMPL)  -dynamiclib -lgfortran -static-libgfortran $(FFLAGD) \
	-o pgprog1 $? -L`pwd` $(PGLOCDIR)/libpgplot.a $(PGLOCDIR)/libXaPgplot.a \
	$(PGLOCDIR)/libXmPgplot.a $(PGLOCDIR)/libX11.a $(PGLOCDIR)/libxcb.a \
	$(PGLOCDIR)/libXau.a $(PGLOCDIR)/libXdmcp.a \
	$(PGLOCDIR)/libpng16.a $(PGLOCDIR)/libz.a $(PGLOCDIR)/libquadmath.a -ldl

#-----------------------------------------------------------------------
# Target "clean" is used to remove all the intermediate files.
#-----------------------------------------------------------------------
clean :
	$(RM)  $(TARGETS) pgdem1$(OEXT) pgex0$(OEXT) pgex1$(OEXT) simple$(OEXT) cpgdemo$(OEXT)
#-----------------------------------------------------------------------
# Target "clean" is used to remove also the output files.
#-----------------------------------------------------------------------
distclean : clean
	$(RM)  $(TARGETS) pgdem1$(OEXT) pgex0$(OEXT) pgex1$(OEXT) simple$(OEXT) cpgdemo$(OEXT) $(OUTFILE)

#-----------------------------------------------------------------------
# Include file dependencies
#-----------------------------------------------------------------------
