C*GREXEC -- PGPLOT device handler dispatch routine
C+
      SUBROUTINE GREXEC(IDEV,IFUNC,RBUF,NBUF,CHR,LCHR)
      INTEGER IDEV, IFUNC, NBUF, LCHR
      REAL    RBUF(*)
      CHARACTER*(*) CHR
C---
      INTEGER NDEV
      PARAMETER (NDEV=23)
      CHARACTER*10 MSG
C---
      GOTO(1,2,3,4,5,6,7,8,9,10,11,12,13,14,
     +     15,16,17,18,19,20,21,22,23) IDEV
      IF (IDEV.EQ.0) THEN
          RBUF(1) = NDEV
          NBUF = 1
      ELSE
          WRITE (MSG,'(I10)') IDEV
          CALL GRWARN('Unknown device code in GREXEC: '//MSG)
      END IF
      RETURN
C---
1     CALL GIDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,1)
      RETURN
2     CALL GIDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,2)
      RETURN
3     CALL NUDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
4     CALL PGDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
5     CALL PNDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,1)
      RETURN
6     CALL PNDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,2)
      RETURN
7     CALL PPDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,1)
      RETURN
8     CALL PPDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,2)
      RETURN
9     CALL PSDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,1)
      RETURN
10    CALL PSDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,2)
      RETURN
11    CALL PSDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,3)
      RETURN
12    CALL PSDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,4)
      RETURN
13    CALL TTDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,5)
      RETURN
14    CALL TTDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,8)
      RETURN
15    CALL TTDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,9)
      RETURN
16    CALL WDDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,1)
      RETURN
17    CALL WDDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,2)
      RETURN
18    CALL X2DRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
19    CALL XWDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,1)
      RETURN
20    CALL XWDRIV(IFUNC,RBUF,NBUF,CHR,LCHR,2)
      RETURN
21    CALL XMDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
22    CALL XADRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
23    CALL TKDRIV(IFUNC,RBUF,NBUF,CHR,LCHR)
      RETURN
C
      END
